name: Update Portfolio Data

on:
  schedule:
    # Run every 15 minutes during market hours (9:30 AM - 4:00 PM ET, Mon-Fri)
    - cron: '*/15 14-21 * * 1-5'  # UTC time (ET + 5 hours)
  workflow_dispatch: # Allow manual trigger

jobs:
  update-portfolio:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Update Portfolio Data
      env:
        QUESTRADE_REFRESH_TOKEN: ${{ secrets.QUESTRADE_REFRESH_TOKEN }}
        CHALLENGE_START_DATE: ${{ secrets.CHALLENGE_START_DATE }}
      run: |
        node update-portfolio.js
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add portfolio-data.json
        git diff --staged --quiet || git commit -m "Update portfolio data - $(date)"
        git push
